version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ferris_file_sync
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
